spring:
  application:
    name: server3

server:
  port: 1113

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka,http://localhost:1112/eureka
  instance:
    hostname: localhost