spring:
  application:
    name: server

server:
  port: 1112

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka,http://localhost:1113/eureka
  instance:
    hostname: server2
  server:
    enableSelfPreservation: false