spring:
  application:
    name: server

server:
  port: 1111

eureka:
  client:
    service-url:
         defaultZone: http://localhost:1112/eureka,http://localhost:1113/eureka
  instance:
    hostname: server1
  server:
    enableSelfPreservation: false